# SPDX-FileCopyrightText: 2022-2023 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = [
    "examples/saved_outputs/**/*.pickle",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (C) 2022-2023 Mitsubishi Electric Research Laboratories (MERL)"
SPDX-License-Identifier = "AGPL-3.0-or-later"
